---
version: "3"

services:
  desktainer:
    image: dmotte/desktainer
    build: docker-build
    restart: always
    hostname: desktainer
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      RESOLUTION: 1440x900
      USER: root
      PASSWORD: debian
      VNC_PASSWORD: debian
